#!/bin/bash

#  View tomcat log while developing.

if [ "$(uname)" != "Darwin" ]; then
	SCRIPT_DIR=`dirname $(readlink -f $0)`
	cd $SCRIPT_DIR
fi

if [ ! -f tomcat/logs/catalina.out ]; then
	echo Waiting for system startup
	while [ ! -f tomcat/logs/catalina.out ]; do
		sleep .1
	done
fi

tail -F tomcat/logs/catalina.out
