/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;
import javax.persistence.*;

/**
 * ProjectStatus generated by hbm2java
 */
@Entity
@Table(name = "appointment_person_join")
public class AppointmentPersonJoin extends ArahantBean implements java.io.Serializable, Comparable<AppointmentPersonJoin> {

	private static final long serialVersionUID = 1L;
	public static final String TABLE_NAME = "appointment_person_join";
	public static final String APPOINTMENT = "appointment";
	public static final String PERSON = "person";
	public static final String PRIMARY = "primaryPerson";
	// Fields    
	private String joinId;
	private Appointment appointment;
	private Person person;
	private char primaryPerson = 'N';

	@Override
	public boolean equals(Object o) {
		if (joinId == null && o == null)
			return true;
		if (joinId != null && o instanceof AppointmentPersonJoin)
			return joinId.equals(((AppointmentPersonJoin) o).getJoinId());

		return false;
	}

	@Override
	public int hashCode() {
		if (joinId == null)
			return 0;
		return joinId.hashCode();
	}

	@Override
	public int compareTo(AppointmentPersonJoin o) {
		if (primaryPerson == 'Y')
			return -1;
		if (o.primaryPerson == 'Y')
			return 1;
		return 0;
	}

	@Override
	public String tableName() {
		return TABLE_NAME;
	}

	@Override
	public String keyColumn() {
		return "join_id";
	}

	@Override
	public String generateId() throws ArahantException {
		return joinId = IDGenerator.generate(this);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appointment_id")
	public Appointment getAppointment() {
		return appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id")
	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Id
	@Column(name = "join_id")
	public String getJoinId() {
		return joinId;
	}

	public void setJoinId(String joinId) {
		this.joinId = joinId;
	}

	@Column(name = "primary_person")
	public char getPrimaryPerson() {
		return primaryPerson;
	}

	public void setPrimaryPerson(char primaryPerson) {
		this.primaryPerson = primaryPerson;
	}
}
