/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;


  
/**
 * HrAccrual generated by hbm2java
 */
@Entity
@Table(name="hr_benefit_rider")
public class BenefitRider extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_benefit_rider";

	// Fields    

	private String benefitRiderId;

	public static final String BENEFIT_RIDER_ID = "benefitRiderId";

	private HrBenefit riderBenefit;

	public static final String RIDER_BENEFIT = "riderBenefit";

	private String riderBenefitId;

	public static final String RIDER_BENEFIT_ID = "riderBenefitId";

	private HrBenefit baseBenefit;

	public static final String  BASE_BENEFIT = "baseBenefit";

	private String baseBenefitId;

	public static final String  BASE_BENEFIT_ID = "baseBenefitId";

	private char hidden = 'N';

	public static final String HIDDEN = "hidden";

	private char required = 'N';

	public static final String REQUIRED = "required";


	// Constructors

	/** default constructor */
	public BenefitRider() {
		super();
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="base_benefit_id")
	public HrBenefit getBaseBenefit() {
		return baseBenefit;
	}

	public void setBaseBenefit(HrBenefit baseBenefit) {
		this.baseBenefit = baseBenefit;
	}

	@Column (name="base_benefit_id", insertable=false, updatable=false)
	public String getBaseBenefitId() {
		return baseBenefitId;
	}

	public void setBaseBenefitId(String baseBenefitId) {
		this.baseBenefitId = baseBenefitId;
	}

	@Id
	@Column (name="benefit_rider_id")
	public String getBenefitRiderId() {
		return benefitRiderId;
	}

	public void setBenefitRiderId(String benefitRiderId) {
		this.benefitRiderId = benefitRiderId;
	}

	@Column (name="hidden")
	public char getHidden() {
		return hidden;
	}

	public void setHidden(char hidden) {
		this.hidden = hidden;
	}

	@Column (name="required")
	public char getRequired() {
		return required;
	}

	public void setRequired(char required) {
		this.required = required;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="rider_benefit_id")
	public HrBenefit getRiderBenefit() {
		return riderBenefit;
	}

	public void setRiderBenefit(HrBenefit riderBenefit) {
		this.riderBenefit = riderBenefit;
	}

	@Column (name="rider_benefit_id", insertable=false, updatable=false)
	public String getRiderBenefitId() {
		return riderBenefitId;
	}

	public void setRiderBenefitId(String riderBenefitId) {
		this.riderBenefitId = riderBenefitId;
	}


	

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	@Override
	public String keyColumn() {
		
		return "benefit_rider_id";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {
		
		return TABLE_NAME;
	}
	

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setBenefitRiderId(IDGenerator.generate(this));
		return benefitRiderId;
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (benefitRiderId==null && o==null)
			return true;
		if (benefitRiderId!=null && o instanceof BenefitRider)
			return benefitRiderId.equals(((BenefitRider)o).getBenefitRiderId());
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		if (benefitRiderId==null)
			return 0;
		return benefitRiderId.hashCode();
	}
}
