/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;



/**
 * HrWage generated by hbm2java
 */
@Entity
@Table(name="benefit_restriction")
public class BenefitRestriction extends ArahantBean implements java.io.Serializable, ArahantSaveNotify {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "benefit_restriction";

	// Fields    

	private String benefitRestrictionId;

	public static final String BENEFIT_RESTRICTION_ID = "benefitRestrictionId";

	private HrBenefitChangeReason benefitChangeReason;

	public static final String BENEFIT_CHANGE_REASON = "benefitChangeReason";

	private String benefitChangeReasonId;;

	public static final String BENEFIT_CHANGE_REASON_ID = "benefitChangeReasonId";

	private HrBenefitCategory benefitCategory;

	public static final String BENEFIT_CATEGORY = "benefitCategory";

	private String benefitCategoryId;

	public static final String BENEFIT_CATEGORY_ID = "benefitCategoryId";
	

	// Constructors

	/** default constructor */
	public BenefitRestriction() {
	}

	
	// Property accessors
	@Id
	@Column (name="benefit_restriction_id")
	public String getBenefitRestrictionId() {
		return this.benefitRestrictionId;
	}

	public void setBenefitRestrictionId(final String benefitRestrictionId) {
		this.benefitRestrictionId = benefitRestrictionId;
	}

	
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	@Override
	public String keyColumn() {
		
		return "benefit_restriction_id";
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="benefit_cat_id")
	public HrBenefitCategory getBenefitCategory() {
		return benefitCategory;
	}

	public void setBenefitCategory(HrBenefitCategory benefitCategory) {
		this.benefitCategory = benefitCategory;
	}

	@Column (name="benefit_cat_id", insertable=false, updatable=false)
	public String getBenefitCategoryId() {
		return benefitCategoryId;
	}

	public void setBenefitCategoryId(String benefitCategoryId) {
		this.benefitCategoryId = benefitCategoryId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="bcr_id")
	public HrBenefitChangeReason getBenefitChangeReason() {
		return benefitChangeReason;
	}

	public void setBenefitChangeReason(HrBenefitChangeReason benefitChangeReason) {
		this.benefitChangeReason = benefitChangeReason;
	}

	@Column (name="bcr_id", insertable=false, updatable=false)
	public String getBenefitChangeReasonId() {
		return benefitChangeReasonId;
	}

	public void setBenefitChangeReasonId(String benefitChangeReasonId) {
		this.benefitChangeReasonId = benefitChangeReasonId;
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {
		
		return TABLE_NAME;
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setBenefitRestrictionId(IDGenerator.generate(this));
		return benefitRestrictionId;
	}
	

    @Override
	public boolean equals(Object o)
	{
		if (benefitRestrictionId==null && o==null)
			return true;
		if (benefitRestrictionId!=null && o instanceof BenefitRestriction)
			return benefitRestrictionId.equals(((BenefitRestriction)o).getBenefitRestrictionId());
		
		return false;
	}
	
    @Override
	public int hashCode()
	{
		if (benefitRestrictionId==null)
			return 0;
		return benefitRestrictionId.hashCode();
	}

	@Override
	public String notifyId() {
		return benefitRestrictionId;
	}

	@Override
	public String notifyClassName() {
		return "BenefitRestriction";
	}
	
	
}
