/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;



import java.util.Date;

import com.arahant.exceptions.ArahantException;

/**
 * DynaceMutex generated by hbm2java
 */
@Entity
@Table(name="dynace_mutex")
public class DynaceMutex extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "dynace_mutex";

	

	// Fields    

	private String tag;

	public static final String TAG = "tag";

	private String data;

	public static final String DATA = "data";

	private Date lastupdate;

	public static final String LASTUPDATE = "lastupdate";

	// Constructors

	/** default constructor */
	public DynaceMutex() {
	}

	/** minimal constructor */
	public DynaceMutex(final String tag, final Date lastupdate) {
		this.tag = tag;
		this.lastupdate = lastupdate;
	}

	/** full constructor */
	public DynaceMutex(final String tag, final String data, final Date lastupdate) {
		this.tag = tag;
		this.data = data;
		this.lastupdate = lastupdate;
	}

	// Property accessors
	@Id
	@Column (name="tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(final String tag) {
		this.tag = tag;
	}

	@Column (name="data")
	public String getData() {
		return this.data;
	}

	public void setData(final String data) {
		this.data = data;
	}

	@Column (name="lastupdate")
	@Temporal (TemporalType.TIMESTAMP)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(final Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	public String keyColumn() {
		
		return "tag";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	public String tableName() {
		
		return TABLE_NAME;
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	public String generateId() throws ArahantException {
		throw new ArahantException("Can't generate like this.");
	}
	

	public boolean equals(Object o)
	{
		if (tag==null && o==null)
			return true;
		if (tag!=null && o instanceof DynaceMutex)
			return tag.equals(((DynaceMutex)o).tag);
		
		return false;
	}
	
	public int hashCode()
	{
		if (tag==null)
			return 0;
		return tag.hashCode();
	}
}
