/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;



/**
 * DynaceSequence generated by hbm2java
 */
@Entity
@Table(name="dynace_sequence")
public class DynaceSequence extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "dynace_sequence";

	

	// Fields    

	private String tag;

	public static final String TAG = "tag";

	private int lastvalue;

	public static final String LASTVALUE = "lastvalue";

	// Constructors

	/** default constructor */
	public DynaceSequence() {
	}

	/** full constructor */
	public DynaceSequence(final String tag, final int lastvalue) {
		this.tag = tag;
		this.lastvalue = lastvalue;
	}

	// Property accessors
	@Id
	@Column (name="tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(final String tag) {
		this.tag = tag;
	}

	@Column (name="lastvalue")
	public int getLastvalue() {
		return this.lastvalue;
	}

	public void setLastvalue(final int lastvalue) {
		this.lastvalue = lastvalue;
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	public String keyColumn() {
		
		return TAG;
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	public String tableName() {
		
		return TABLE_NAME;
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	public String generateId() throws ArahantException {
		throw new ArahantException("Can't generate like this.");
	}
	

	public boolean equals(Object o)
	{
		if (tag==null && o==null)
			return true;
		if (tag!=null && o instanceof DynaceSequence)
			return tag.equals(((DynaceSequence)o).tag);
		
		return false;
	}
	
	public int hashCode()
	{
		if (tag==null)
			return 0;
		return tag.hashCode();
	}
}
