/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;
import javax.persistence.*;

/**
 * Holiday generated by hbm2java
 */
@Entity
@Table(name = "holiday")
public class Holiday extends Filtered implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String TABLE_NAME = "holiday";
	public static final char FULL_DAY = 'F';
	public static final char FIRST_HALF = '1';
	public static final char SECOND_HALF = '2';
	// Fields    
	private String holidayId;
	public static final String HOLIDAYID = "holidayId";
	private int hdate;
	public static final String HDATE = "hdate";
	private String description;
	public static final String DESCRIPTION = "description";
	private char partOfDay = 'F';

	// Constructors
	/**
	 * default constructor
	 */
	public Holiday() {
		super();
	}

	@Override
	@ManyToOne
	@JoinColumn(name = "org_group_id")
	public OrgGroup getOrgGroup() {
		return orgGroup;
	}

	/**
	 * @return Returns the description.
	 */
	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	/**
	 * @param description The description to set.
	 */
	public void setDescription(String description) {
		firePropertyChange("description", this.description, description);
		this.description = description;
	}

	/**
	 * @return Returns the hdate.
	 */
	@Column(name = "hdate")
	public int getHdate() {
		return hdate;
	}

	/**
	 * @param hdate The hdate to set.
	 */
	public void setHdate(int hdate) {
		firePropertyChange("hdate", this.hdate, hdate);
		this.hdate = hdate;
	}

	/**
	 * @return Returns the holidayId.
	 */
	@Id
	@Column(name = "holiday_id")
	public String getHolidayId() {
		return holidayId;
	}

	/**
	 * @param holidayId The holidayId to set.
	 */
	public void setHolidayId(String holidayId) {
		firePropertyChange("holidayId", this.holidayId, holidayId);
		this.holidayId = holidayId;
	}

	@Column(name = "part_of_day")
	public char getPartOfDay() {
		return partOfDay;
	}

	public void setPartOfDay(char partOfDay) {
		this.partOfDay = partOfDay;
	}

	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	@Override
	public String keyColumn() {

		return "holiday_id";
	}

	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {

		return TABLE_NAME;
	}

	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setHolidayId(IDGenerator.generate(this));
		return holidayId;
	}

	@Override
	public boolean equals(Object o) {
		if (holidayId == null && o == null)
			return true;
		if (holidayId != null && o instanceof Holiday)
			return holidayId.equals(((Holiday) o).getHolidayId());

		return false;
	}

	@Override
	public int hashCode() {
		if (holidayId == null)
			return 0;
		return holidayId.hashCode();
	}
}
