/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;


  
/**
 * HrAccrual generated by hbm2java
 */
@Entity
@Table(name="hr_accrual")
public class HrAccrual extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_accrual";

	

	// Fields    

	private String accrualId;

	public static final String ACCRUALID = "accrualId";

	private Timesheet timesheet;

	//public static final String TIMESHEET = "timesheet";

	private Person employee;

	public static final String EMPLOYEE = "employee";

	private HrBenefit hrBenefit;

	public static final String HRBENEFIT = "hrBenefit";

	private int accrualDate;

	public static final String ACCRUALDATE = "accrualDate";

	private double accrualHours;

	public static final String ACCRUALHOURS = "accrualHours";

	private String description;

	public static final String DESCRIPTION = "description";


	// Constructors

	/** default constructor */
	public HrAccrual() {
		super();
	}


	
	/**
	 * @return Returns the accrualDate.
	 */
	@Column (name="accrual_date")
	public int getAccrualDate() {
		return accrualDate;
	}



	/**
	 * @param accrualDate The accrualDate to set.
	 */
	public void setAccrualDate(int accrualDate) {
		firePropertyChange("accrualDate", this.accrualDate, accrualDate);
		this.accrualDate = accrualDate;
	}



	/**
	 * @return Returns the accrualHours.
	 */
	@Column (name="accrual_hours")
	public double getAccrualHours() {
		return accrualHours;
	}



	/**
	 * @param accrualHours The accrualHours to set.
	 */
	public void setAccrualHours(double accrualHours) {
		firePropertyChange("accrualHours", this.accrualHours, accrualHours);
		this.accrualHours = accrualHours;
	}



	/**
	 * @return Returns the accrualId.
	 */
	@Id
	@Column (name="accrual_id")
	public String getAccrualId() {
		return accrualId;
	}



	/**
	 * @param accrualId The accrualId to set.
	 */
	public void setAccrualId(String accrualId) {
		firePropertyChange("accrualId", this.accrualId, accrualId);
		this.accrualId = accrualId;
	}



	/**
	 * @return Returns the description.
	 */
	@Column (name="description")
	public String getDescription() {
		return description;
	}



	/**
	 * @param description The description to set.
	 */
	public void setDescription(String description) {
		if (description!=null && description.length()>80)
			description=description.substring(0, 80);

		firePropertyChange("description", this.description, description);
		this.description = description;
	}



	/**
	 * @return Returns the employee.
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="employee_id")
	public Person getEmployee() {
		return employee;
	}



	/**
	 * @param employee The employee to set.
	 */
	public void setEmployee(Person employee) {
		this.employee = employee;
	}



	/**
	 * @return Returns the hrBenefit.
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="benefit_account")
	public HrBenefit getHrBenefit() {
		return hrBenefit;
	}



	/**
	 * @param hrBenefit The hrBenefit to set.
	 */
	public void setHrBenefit(HrBenefit hrBenefit) {
		this.hrBenefit = hrBenefit;
	}



	/**
	 * @return Returns the timesheet.
	 */
//	@ManyToOne(fetch=FetchType.LAZY)
//	@JoinColumn (name="timesheet_id")
//	public Timesheet getTimesheet() {
//		return timesheet;
//	}



	/**
	 * @param timesheet The timesheet to set.
	 */
//	public void setTimesheet(Timesheet timesheet) {
//		this.timesheet = timesheet;
//	}





	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	@Override
	public String keyColumn() {
		
		return "accrual_id";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {
		
		return TABLE_NAME;
	}
	

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setAccrualId(IDGenerator.generate(this));
		return accrualId;
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (accrualId==null && o==null)
			return true;
		if (accrualId!=null && o instanceof HrAccrual)
			return accrualId.equals(((HrAccrual)o).getAccrualId());
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		if (accrualId==null)
			return 0;
		return accrualId.hashCode();
	}
}
