/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;



/**
 * HrBenefitProjectJoin generated by hbm2java
 */
@Entity
@Table(name="hr_benefit_project_join")
public class HrBenefitProjectJoin extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_benefit_project_join";

	

	// Fields    
	
	private HrBenefitProjectJoinId id;

	public static final String ID = "id";

	private HrBenefitConfig hrBenefitConfig;

	public static final String HR_BENEFIT_CONFIG = "hrBenefitConfig";

	private Project project;

	public static final String PROJECT = "project";

	// Constructors

	/** default constructor */
	public HrBenefitProjectJoin() {
	}

	// Property accessors
	@Id
	public HrBenefitProjectJoinId getId() {
		return this.id;
	}

	public void setId(final HrBenefitProjectJoinId id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="benefit_config_id",updatable=false,insertable=false)
	public HrBenefitConfig getHrBenefitConfig() {
		return this.hrBenefitConfig;
	}

	public void setHrBenefitConfig(final HrBenefitConfig hrBenefit) {
		this.hrBenefitConfig = hrBenefit;
		if (id==null)
			id=new HrBenefitProjectJoinId();
		id.setBenefitConfigId(hrBenefit!=null?hrBenefit.getBenefitConfigId():null);
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="project_id",updatable=false,insertable=false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(final Project project) {
		this.project = project;
		if (id==null)
			id=new HrBenefitProjectJoinId();
		id.setProjectId(project!=null?project.getProjectId():null);
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	public String keyColumn() {
		
		return "";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	public String tableName() {
		
		return TABLE_NAME;
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	public String generateId() throws ArahantException {
		throw new ArahantException("Can't generate like this.");
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (id==null && o==null)
			return true;
		if (id!=null && o instanceof HrBenefitProjectJoin)
			return id.equals(((HrBenefitProjectJoin)o).getId());
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		if (id==null)
			return 0;
		return id.hashCode();
	}
}
