/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import javax.persistence.*;



import java.util.HashSet;
import java.util.Set;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;

/**
 * HrBenefitPackage generated by hbm2java
 */
@Entity
@Table(name = "hr_benefit_package")
public class HrBenefitPackage extends ArahantBean implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "hr_benefit_package";
    // Fields
    private String packageId;
    public static final String PACKAGEID = "packageId";
    private String name;
    public static final String NAME = "name";
    private Set<HrBenefitPackageJoin> hrBenefitPackageJoins = new HashSet<HrBenefitPackageJoin>(0);
    public static final String HRBENEFITPACKAGEJOINS = "hrBenefitPackageJoins";

    // Constructors
    /** default constructor */
    public HrBenefitPackage() {
        super();
    }


    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#keyColumn()
     */
    @Override
    public String keyColumn() {

        return "package_id";
    }

    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#tableName()
     */
    @Override
    public String tableName() {

        return TABLE_NAME;
    }
    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#generateId()
     */

    @Override
    public String generateId() throws ArahantException {
        setPackageId(IDGenerator.generate(this));
        return packageId;
    }

    /**
     * @return Returns the hrBenefitPackageJoins.
     */
    @OneToMany(mappedBy = HrBenefitPackageJoin.HRBENEFITPACKAGE, fetch = FetchType.LAZY)
    @org.hibernate.annotations.Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    public Set<HrBenefitPackageJoin> getHrBenefitPackageJoins() {
        return hrBenefitPackageJoins;
    }

    /**
     * @param hrBenefitPackageJoins The hrBenefitPackageJoins to set.
     */
    public void setHrBenefitPackageJoins(
            Set<HrBenefitPackageJoin> hrBenefitPackageJoins) {

        this.hrBenefitPackageJoins = hrBenefitPackageJoins;
    }

    /**
     * @return Returns the name.
     */
    @Column(name = "name")
    public String getName() {
        return name;
    }

    /**
     * @param name The name to set.
     */
    public void setName(String name) {
        firePropertyChange("name", this.name, name);
        this.name = name;
    }

    /**
     * @return Returns the packageId.
     */
    @Id
    @Column(name = "package_id")
    public String getPackageId() {
        return packageId;
    }

    /**
     * @param packageId The packageId to set.
     */
    public void setPackageId(String packageId) {
        firePropertyChange("packageId", this.packageId, packageId);
        this.packageId = packageId;
    }

    @Override
    public boolean equals(Object o) {
        if (packageId == null && o == null) {
            return true;
        }
        if (packageId != null && o instanceof HrBenefitPackage) {
            return packageId.equals(((HrBenefitPackage) o).getPackageId());
        }

        return false;
    }

    @Override
    public int hashCode() {
        if (packageId == null) {
            return 0;
        }
        return packageId.hashCode();
    }
}
