/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;



/**
 * HrBenefitPackageJoinId generated by hbm2java
 */
@Embeddable
public class HrBenefitPackageJoinId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_benefit_package_join";

	

	// Fields    

	private String packageId;

	public static final String PACKAGEID = "packageId";

	private String benefitId;

	public static final String BENEFITID = "benefitId";

	// Constructors

	/** default constructor */
	public HrBenefitPackageJoinId() {
	}

	/** full constructor */
	public HrBenefitPackageJoinId(final String packageId, final String benefitId) {
		this.packageId = packageId;
		this.benefitId = benefitId;
	}

	// Property accessors
	@Column(name="package_id")
	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(final String packageId) {
		this.packageId = packageId;
	}

	@Column(name="benefit_id")
	public String getBenefitId() {
		return this.benefitId;
	}

	public void setBenefitId(final String benefitId) {
		this.benefitId = benefitId;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrBenefitPackageJoinId))
			return false;
		final HrBenefitPackageJoinId castOther = (HrBenefitPackageJoinId) other;

		return ((this.getPackageId() == castOther.getPackageId()) || (this
				.getPackageId() != null
				&& castOther.getPackageId() != null && this.getPackageId()
				.equals(castOther.getPackageId())))
				&& ((this.getBenefitId() == castOther.getBenefitId()) || (this
						.getBenefitId() != null
						&& castOther.getBenefitId() != null && this
						.getBenefitId().equals(castOther.getBenefitId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPackageId() == null ? 0 : this.getPackageId().hashCode());
		result = 37 * result
				+ (getBenefitId() == null ? 0 : this.getBenefitId().hashCode());
		return result;
	}

}
