/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;



/**
 * HrBenefitPackageJoin generated by hbm2java
 */
@Entity
@Table(name="hr_benefit_package_join")
public class HrBenefitPackageJoin extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_benefit_package_join";

	

	// Fields    

	private HrBenefitPackageJoinId id;

	public static final String ID = "id";

	private HrBenefitPackage hrBenefitPackage;

	public static final String HRBENEFITPACKAGE = "hrBenefitPackage";

	private HrBenefit hrBenefit;

	public static final String HRBENEFIT = "hrBenefit";

	// Constructors

	/** default constructor */
	public HrBenefitPackageJoin() {
	}



	// Property accessors
	@Id
	public HrBenefitPackageJoinId getId() {
		return this.id;
	}

	public void setId(final HrBenefitPackageJoinId id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="package_id",updatable=false,insertable=false)
	public HrBenefitPackage getHrBenefitPackage() {
		return this.hrBenefitPackage;
	}

	public void setHrBenefitPackage(final HrBenefitPackage hrBenefitPackage) {
		this.hrBenefitPackage = hrBenefitPackage;
		if (id==null)
			id=new HrBenefitPackageJoinId();
		id.setPackageId(hrBenefitPackage!=null?hrBenefitPackage.getPackageId():null);
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="benefit_id",updatable=false,insertable=false)
	public HrBenefit getHrBenefit() {
		return this.hrBenefit;
	}

	public void setHrBenefit(final HrBenefit hrBenefit) {
		this.hrBenefit = hrBenefit;
		if (id==null)
			id=new HrBenefitPackageJoinId();
		id.setBenefitId(hrBenefit!=null?hrBenefit.getBenefitId():null);
	}
	
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	public String keyColumn() {
		
		return "";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	public String tableName() {
		
		return TABLE_NAME;
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	public String generateId() throws ArahantException {
		throw new ArahantException("Can't generate like this.");
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (id==null && o==null)
			return true;
		if (id!=null && o instanceof HrBenefitPackageJoin)
			return id.equals(((HrBenefitPackageJoin)o).getId());
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		if (id==null)
			return 0;
		return id.hashCode();
	}
}
