/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import javax.persistence.*;



import java.util.HashSet;
import java.util.Set;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;

/**
 * HrChecklistItem generated by hbm2java
 */
@Entity
@Table(name = "hr_checklist_item")
public class HrChecklistItem extends Setup implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "hr_checklist_item";
    // Fields

	public static final char RESPONSIBILITY_MANAGER='M';
	public static final char RESPONSIBILITY_HR='H';
	public static final char RESPONSIBILITY_EMPLOYEE='E';

    private String itemId;
    public static final String ITEMID = "itemId";
    private HrEmployeeStatus hrEmployeeStatus;
    public static final String HREMPLOYEESTATUS = "hrEmployeeStatus";
    private String name;
    public static final String NAME = "name";
    private short seq;
    public static final String SEQ = "seq";
    private Set<HrChecklistDetail> hrChecklistDetails = new HashSet<HrChecklistDetail>(0);
    public static final String HRCHECKLISTDETAILS = "hrChecklistDetails";
	private char responsibility;
	public static final String RESPONSIBILITY = "responsibility";
	public static final String SCREEN = "screen";
	public static final String SCREEN_GROUP = "screenGroup";
	private Screen screen;
	public static final String SCREEN_ID = "screenId";
	public static final String SCREEN_GROUP_ID = "screenGroupId";
	private String screenId;
	private String screenGroupId;
	private ScreenGroup screenGroup;
	private CompanyForm companyForm;
	private String companyFormId;
	public static final String COMPANY_FORM = "companyForm";
	public static final String COMPANY_FORM_ID = "companyFormId";


    // Constructors
    /** default constructor */
    public HrChecklistItem() {
    }

    // Property accessors
    @Id
    @Column(name = "item_id")
    public String getItemId() {
        return this.itemId;
    }

    public void setItemId(final String itemId) {
        this.itemId = itemId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_status_id")
    public HrEmployeeStatus getHrEmployeeStatus() {
        return this.hrEmployeeStatus;
    }

    public void setHrEmployeeStatus(final HrEmployeeStatus hrEmployeeStatus) {
        this.hrEmployeeStatus = hrEmployeeStatus;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Column(name = "seq")
    public short getSeq() {
        return this.seq;
    }

    public void setSeq(final short seq) {
        this.seq = seq;
    }

	@ManyToOne
    @JoinColumn(name = "company_form_id")
	public CompanyForm getCompanyForm() {
		return companyForm;
	}

	public void setCompanyForm(CompanyForm companyForm) {
		this.companyForm = companyForm;
	}

	@Column(name="company_form_id", insertable=false, updatable=false)
	public String getCompanyFormId() {
		return companyFormId;
	}

	public void setCompanyFormId(String companyFormId) {
		this.companyFormId = companyFormId;
	}

    @OneToMany(mappedBy = HrChecklistDetail.HRCHECKLISTITEM, fetch = FetchType.LAZY)
    @org.hibernate.annotations.Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    public Set<HrChecklistDetail> getHrChecklistDetails() {
        return this.hrChecklistDetails;
    }

    public void setHrChecklistDetails(final Set<HrChecklistDetail> hrChecklistDetails) {
        this.hrChecklistDetails = hrChecklistDetails;
    }

    @Column(name = "last_active_date")
    @Override
    public int getLastActiveDate() {
        return lastActiveDate;
    }

    @Column(name = "first_active_date")
    @Override
    public int getFirstActiveDate() {
        return firstActiveDate;
    }

    @ManyToOne
    @JoinColumn(name = "org_group_id")
    @Override
    public OrgGroup getOrgGroup() {
        return orgGroup;
    }

	@Column(name="responsibility")
	public char getResponsibility() {
		return responsibility;
	}

	public void setResponsibility(final char responsibility) {
		this.responsibility = responsibility;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="screen_id")
	public Screen getScreen() {
		return screen;
	}

	public void setScreen(Screen screen) {
		this.screen = screen;
	}

	@Column(name="screen_group_id", insertable=false, updatable=false)
	public String getScreenGroupId() {
		return screenGroupId;
	}

	public void setScreenGroupId(String screenGroupId) {
		this.screenGroupId = screenGroupId;
	}

	@Column(name="screen_id", insertable=false, updatable=false)
	public String getScreenId() {
		return screenId;
	}

	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="screen_group_id")
	public ScreenGroup getScreenGroup() {
		return screenGroup;
	}

	public void setScreenGroup(ScreenGroup screenGroup) {
		this.screenGroup = screenGroup;
	}

    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#keyColumn()
     */
    @Override
    public String keyColumn() {

        return "item_id";
    }

    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#tableName()
     */
    @Override
    public String tableName() {

        return TABLE_NAME;
    }

    /* (non-Javadoc)
     * @see com.arahant.beans.ArahantBean#generateId()
     */
    @Override
    public String generateId() throws ArahantException {
        setItemId(IDGenerator.generate(this));
        return itemId;
    }

    @Override
    public boolean equals(Object o) {
        if (itemId == null && o == null) {
            return true;
        }
        if (itemId != null && o instanceof HrChecklistItem) {
            return itemId.equals(((HrChecklistItem) o).getItemId());
        }

        return false;
    }

    @Override
    public int hashCode() {
        if (itemId == null) {
            return 0;
        }
        return itemId.hashCode();
    }
}
