/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;
import java.util.Date;



/**
 * HrChecklistDetail generated by hbm2java
 */
@Entity
@Table(name="hr_checklist_detail")
public class HrChecklistDetail extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_checklist_detail";

	// Fields    

	private String checklistDetailId;

	public static final String CHECKLISTDETAILID = "checklistDetailId";

	private Person employeeByEmployeeId;

	public static final String EMPLOYEEBYEMPLOYEEID = "employeeByEmployeeId";

	private Employee employeeBySupervisorId;

	public static final String EMPLOYEEBYSUPERVISORID = "employeeBySupervisorId";

	private HrChecklistItem hrChecklistItem;

	public static final String HRCHECKLISTITEM = "hrChecklistItem";

	private int dateCompleted;

	public static final String DATECOMPLETED = "dateCompleted";

	private int timeCompleted;

	public static final String TIME_COMPLETED = "timeCompleted";

	// Constructors

	/** default constructor */
	public HrChecklistDetail() {
	}

	/** full constructor */
	public HrChecklistDetail(final String checklistDetailId,
			final Person employeeByEmployeeId, final Employee employeeBySupervisorId,
			final HrChecklistItem hrChecklistItem, final int dateCompleted) {
		this.checklistDetailId = checklistDetailId;
		this.employeeByEmployeeId = employeeByEmployeeId;
		this.employeeBySupervisorId = employeeBySupervisorId;
		this.hrChecklistItem = hrChecklistItem;
		this.dateCompleted = dateCompleted;
	}

	// Property accessors
	@Id
	@Column (name="checklist_detail_id")
	public String getChecklistDetailId() {
		return this.checklistDetailId;
	}

	public void setChecklistDetailId(final String checklistDetailId) {
		this.checklistDetailId = checklistDetailId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="employee_id")
	public Person getEmployeeByEmployeeId() {
		return this.employeeByEmployeeId;
	}

	public void setEmployeeByEmployeeId(final Person employeeByEmployeeId) {
		this.employeeByEmployeeId = employeeByEmployeeId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="supervisor_id")
	public Employee getEmployeeBySupervisorId() {
		return this.employeeBySupervisorId;
	}

	public void setEmployeeBySupervisorId(final Employee employeeBySupervisorId) {
		this.employeeBySupervisorId = employeeBySupervisorId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="checklist_item_id")
	public HrChecklistItem getHrChecklistItem() {
		return this.hrChecklistItem;
	}

	public void setHrChecklistItem(final HrChecklistItem hrChecklistItem) {
		this.hrChecklistItem = hrChecklistItem;
	}

	@Column (name="date_completed")
	public int getDateCompleted() {
		return this.dateCompleted;
	}

	public void setDateCompleted(final int dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

	@Column(name="time_completed")
	public int getTimeCompleted() {
		return timeCompleted;
	}

	public void setTimeCompleted(int timeCompleted) {
		this.timeCompleted = timeCompleted;
	}
	
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	@Override
	public String keyColumn() {
		
		return "checklist_detail_id";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {
		
		return TABLE_NAME;
	}
	
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setChecklistDetailId(IDGenerator.generate(this));
		return checklistDetailId;
	}
	
	@Override
	public boolean equals(Object o)
	{
		if (checklistDetailId==null && o==null)
			return true;
		if (checklistDetailId!=null && o instanceof HrChecklistDetail)
			return checklistDetailId.equals(((HrChecklistDetail)o).getChecklistDetailId());
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		if (checklistDetailId==null)
			return 0;
		return checklistDetailId.hashCode();
	}

}
