/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;
import javax.persistence.*;
import org.hibernate.annotations.Fetch;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;



/**
 * HrEmplEvalDetail generated by hbm2java
 */
@Entity
@Table(name="hr_empl_eval_detail")
public class HrEmplEvalDetail extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "hr_empl_eval_detail";
	public static final String EMPOYEE_EVAL="hrEmployeeEval";

	

	// Fields    

	private String detailId;

	public static final String DETAILID = "detailId";

	private HrEmployeeEval hrEmployeeEval;

	public static final String HREMPLOYEEEVAL = "hrEmployeeEval";

	private HrEvalCategory hrEvalCategory;

	public static final String HREVALCATEGORY = "hrEvalCategory";

	private short score;

	public static final String SCORE = "score";

	private String notes;

	public static final String NOTES = "notes";

	private short EScore;

	public static final String ESCORE = "EScore";

	private String ENotes;

	public static final String ENOTES = "ENotes";

	private String PNotes;

	public static final String PNOTES = "PNotes";

	// Constructors

	/** default constructor */
	public HrEmplEvalDetail() {
	}

	/** minimal constructor */
	public HrEmplEvalDetail(final String detailId, final HrEmployeeEval hrEmployeeEval,
			final HrEvalCategory hrEvalCategory, final short score, final short EScore) {
		this.detailId = detailId;
		this.hrEmployeeEval = hrEmployeeEval;
		this.hrEvalCategory = hrEvalCategory;
		this.score = score;
		this.EScore = EScore;
	}

	/** full constructor */
	public HrEmplEvalDetail(final String detailId, final HrEmployeeEval hrEmployeeEval,
			final HrEvalCategory hrEvalCategory, final short score, final String notes,
			final short EScore, final String ENotes, final String PNotes) {
		this.detailId = detailId;
		this.hrEmployeeEval = hrEmployeeEval;
		this.hrEvalCategory = hrEvalCategory;
		this.score = score;
		this.notes = notes;
		this.EScore = EScore;
		this.ENotes = ENotes;
		this.PNotes = PNotes;
	}

	// Property accessors
	@Id
	@Column (name="detail_id")
	public String getDetailId() {
		return this.detailId;
	}

	public void setDetailId(final String detailId) {
		this.detailId = detailId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="eval_id")
	public HrEmployeeEval getHrEmployeeEval() {
		return this.hrEmployeeEval;
	}

	public void setHrEmployeeEval(final HrEmployeeEval hrEmployeeEval) {
		this.hrEmployeeEval = hrEmployeeEval;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn (name="cat_id")
	public HrEvalCategory getHrEvalCategory() {
		return this.hrEvalCategory;
	}

	public void setHrEvalCategory(final HrEvalCategory hrEvalCategory) {
		this.hrEvalCategory = hrEvalCategory;
	}

	@Column (name="score")
	public short getScore() {
		return this.score;
	}

	public void setScore(final short score) {
		this.score = score;
	}

	@Column (name="notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(final String notes) {
		this.notes = notes;
	}

	@Column (name="e_score")
	public short getEScore() {
		return this.EScore;
	}

	public void setEScore(final short EScore) {
		this.EScore = EScore;
	}

	@Column (name="e_notes")
	public String getENotes() {
		return this.ENotes;
	}

	public void setENotes(final String ENotes) {
		this.ENotes = ENotes;
	}

	@Column (name="p_notes")
	public String getPNotes() {
		return this.PNotes;
	}

	public void setPNotes(final String PNotes) {
		this.PNotes = PNotes;
	}
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#keyColumn()
	 */
	public String keyColumn() {
		
		return "detail_id";
	}

	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#tableName()
	 */
	public String tableName() {
		
		return TABLE_NAME;
	}
	
	/* (non-Javadoc)
	 * @see com.arahant.beans.ArahantBean#generateId()
	 */
	public String generateId() throws ArahantException {
		setDetailId(IDGenerator.generate(this));
		return detailId;
	}
	
	public boolean equals(Object o)
	{
		if (detailId==null && o==null)
			return true;
		if (detailId!=null && o instanceof HrEmplEvalDetail)
			return detailId.equals(((HrEmplEvalDetail)o).getDetailId());
		
		return false;
	}
	
	public int hashCode()
	{
		if (detailId==null)
			return 0;
		return detailId.hashCode();
	}
}
