/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import javax.persistence.Column;
import javax.persistence.Embeddable;



/**
 * OrgGroupAssociationId generated by hbm2java
 */
@Embeddable
public class OrgGroupAssociationId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "org_group_association";

	

	// Fields    

	private String personId;

	public static final String PERSONID = "personId";

	private String orgGroupId;

	public static final String ORGGROUPID = "orgGroupId";

	// Constructors

	/** default constructor */
	public OrgGroupAssociationId() {
	}

	/** full constructor */
	public OrgGroupAssociationId(final String personId, final String orgGroupId) {
		this.personId = personId;
		this.orgGroupId = orgGroupId;
	}

	// Property accessors
	@Column(name="person_id")
	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(final String personId) {
		this.personId = personId;
	}

	@Column(name="org_group_id")
	public String getOrgGroupId() {
		return this.orgGroupId;
	}

	public void setOrgGroupId(final String orgGroupId) {
		this.orgGroupId = orgGroupId;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrgGroupAssociationId))
			return false;
		final OrgGroupAssociationId castOther = (OrgGroupAssociationId) other;

		return ((this.getPersonId() == castOther.getPersonId()) || (this
				.getPersonId() != null
				&& castOther.getPersonId() != null && this.getPersonId()
				.equals(castOther.getPersonId())))
				&& ((this.getOrgGroupId() == castOther.getOrgGroupId()) || (this
						.getOrgGroupId() != null
						&& castOther.getOrgGroupId() != null && this
						.getOrgGroupId().equals(castOther.getOrgGroupId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37
				* result
				+ (getOrgGroupId() == null ? 0 : this.getOrgGroupId()
						.hashCode());
		return result;
	}

}
