/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;



/**
 * VendorContact generated by hbm2java
 */
@Entity
@Table(name="prospect_contact")
public class ProspectContact extends Person implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "prospect_contact";

	public static final short TYPE_DECISION_MAKER=1;
	public static final short TYPE_DEPARTMENT_HEAD=2;
	public static final short TYPE_USER=3;
	public static final short TYPE_CONSULTANT=4;
	public static final short TYPE_UNKNOWN=5;

	// Fields    

	// Constructors

	/** default constructor */
	public ProspectContact() {
	}

	private short contactType = TYPE_UNKNOWN;

	@Column(name="contact_type")
	public short getContactType() {
		return contactType;
	}

	public void setContactType(short contactType) {
		this.contactType = contactType;
	}

	
}
