/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import com.arahant.exceptions.ArahantException;
import com.arahant.utils.IDGenerator;
import javax.persistence.*;

/**
 * StandardProject generated by hbm2java
 */
@Entity
@Table(name = "standard_project")
public class StandardProject extends ArahantBean implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String TABLE_NAME = "standard_project";
	// Fields    
	private String projectId;
	public static final String PROJECTID = "projectId";
	private Person person;
	public static final String PERSON = "person";
	private OrgGroup orgGroup;
	public static final String ORGGROUP = "orgGroup";
	private ProjectCategory projectCategory;
	public static final String PROJECTCATEGORY = "projectCategory";
	private Employee employee;
	public static final String EMPLOYEE = "employee";
	private Service productService;
	public static final String PRODUCTSERVICE = "productService";
	private ProjectType projectType;
	public static final String PROJECTTYPE = "projectType";
	private String reference;
	public static final String REFERENCE = "reference";
	private String description;
	public static final String DESCRIPTION = "description";
	private String detailDesc;
	public static final String DETAILDESC = "detailDesc";
	private double dollarCap;
	public static final String DOLLARCAP = "dollarCap";
	private float billingRate;
	public static final String BILLINGRATE = "billingRate";
	private char billable;
	public static final String BILLABLE = "billable";
	private String requesterName;
	public static final String REQUESTERNAME = "requesterName";
	private int billingMethod;
	public static final String BILLINGMETHOD = "billingMethod";
	private int nextBillingDate;
	public static final String NEXTBILLINGDATE = "nextBillingDate";
	private char allEmployees;
	public static final String ALLEMPLOYEES = "allEmployees";
	private CompanyDetail company;
	public static final String COMPANY = "company";
	private String companyId;
	public static final String COMPANY_ID = "companyId";

	// Constructors
	/**
	 * default constructor
	 */
	public StandardProject() {
	}

	// Property accessors
	@Id
	@Column(name = "project_id")
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(final String projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public CompanyDetail getCompany() {
		return company;
	}

	public void setCompany(CompanyDetail company) {
		this.company = company;
	}

	@Column(name = "company_id", insertable = false, updatable = false)
	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_sponsor_id")
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(final Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bill_at_org_group")
	public OrgGroup getOrgGroup() {
		return this.orgGroup;
	}

	public void setOrgGroup(final OrgGroup orgGroup) {
		this.orgGroup = orgGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_category_id")
	public ProjectCategory getProjectCategory() {
		return this.projectCategory;
	}

	public void setProjectCategory(final ProjectCategory projectCategory) {
		this.projectCategory = projectCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "managing_employee")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(final Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Service getProductService() {
		return this.productService;
	}

	public void setProductService(final Service productService) {
		this.productService = productService;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_type_id")
	public ProjectType getProjectType() {
		return this.projectType;
	}

	public void setProjectType(final ProjectType projectType) {
		this.projectType = projectType;
	}

	@Column(name = "reference")
	public String getReference() {
		return this.reference;
	}

	public void setReference(final String reference) {
		this.reference = reference;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(final String description) {
		this.description = description;
	}

	@Column(name = "detail_desc")
	public String getDetailDesc() {
		return this.detailDesc;
	}

	public void setDetailDesc(final String detailDesc) {
		this.detailDesc = detailDesc;
	}

	@Column(name = "dollar_cap")
	public double getDollarCap() {
		return this.dollarCap;
	}

	public void setDollarCap(final double dollarCap) {
		this.dollarCap = dollarCap;
	}

	@Column(name = "billing_rate")
	public float getBillingRate() {
		return this.billingRate;
	}

	public void setBillingRate(final float billingRate) {
		this.billingRate = billingRate;
	}

	@Column(name = "billable")
	public char getBillable() {
		return this.billable;
	}

	public void setBillable(final char billable) {
		this.billable = billable;
	}

	@Column(name = "requester_name")
	public String getRequesterName() {
		return this.requesterName;
	}

	public void setRequesterName(final String requesterName) {
		this.requesterName = requesterName;
	}

	@Column(name = "billing_method")
	public int getBillingMethod() {
		return this.billingMethod;
	}

	public void setBillingMethod(final int billingMethod) {
		this.billingMethod = billingMethod;
	}

	@Column(name = "next_billing_date")
	public int getNextBillingDate() {
		return this.nextBillingDate;
	}

	public void setNextBillingDate(final int nextBillingDate) {
		this.nextBillingDate = nextBillingDate;
	}

	@Column(name = "all_employees")
	public char getAllEmployees() {
		return this.allEmployees;
	}

	public void setAllEmployees(final char allEmployees) {
		this.allEmployees = allEmployees;
	}
	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#keyColumn()
	 */

	@Override
	public String keyColumn() {
		return "project_id";
	}

	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#tableName()
	 */
	@Override
	public String tableName() {
		return TABLE_NAME;
	}


	/*
	 * (non-Javadoc) @see com.arahant.beans.ArahantBean#generateId()
	 */
	@Override
	public String generateId() throws ArahantException {
		setProjectId(IDGenerator.generate(this));
		return projectId;
	}

	@Override
	public boolean equals(Object o) {
		if (projectId == null && o == null)
			return true;
		if (projectId != null && o instanceof StandardProject)
			return projectId.equals(((StandardProject) o).getProjectId());

		return false;
	}

	@Override
	public int hashCode() {
		if (projectId == null)
			return 0;
		return projectId.hashCode();
	}
}
