/*
    STACK360 - Web-based Business Management System
    Copyright (C) 2024 Arahant LLC

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see https://www.gnu.org/licenses.
*/

/*
*/


package com.arahant.beans;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * VendorCompany generated by hbm2java
 */
@Entity
@Table(name = VendorCompany.TABLE_NAME)
public class VendorCompany extends CompanyBase implements java.io.Serializable, ArahantSaveNotify {

	private static final long serialVersionUID = 1L;
	@SuppressWarnings("FieldNameHidesFieldInSuperclass")
	public static final String TABLE_NAME = "vendor";
	// Fields
	private GlAccount glAccountByDfltApAcct;
	public static final String GLACCOUNTBYDFLTAPACCT = "glAccountByDfltApAcct";
	private GlAccount glAccountByDfltExpenseAcct;
	public static final String GLACCOUNTBYDFLTEXPENSEACCT = "glAccountByDfltExpenseAcct";
	private String accountNumber;
	public static final String ACCOUNTNUMBER = "accountNumber";
	private Set<HrBenefit> benefitsProvided = new HashSet<HrBenefit>();
	public static final String PROVIDED_BENEFITS = "benefitsProvided";
	private CompanyDetail associatedCompany;
	public static final String ASSOCIATED_COMPANY = "associatedCompany";
	private short interfaceId;
	public static final String INTERFACE_ID = "interfaceId";
	/*
	 * Here is where the interface ID's are defined.
	 *
	 * If this list gets changed you must also change
	 * com.arahant.services.standard.misc.vendor.VendorOps.java Method
	 * listEdiInterfaces()
	 */
	public static final short CONSOCIATES = 1;
	public static final short VSP = 2;
	public static final short BCBS = 3;
	public static final short BCN = 4;
	public static final short HUMANA = 5;
	public static final short EBC = 6;
	public static final short EHIM = 7;
	public static final short DELTA_DENTAL = 8;
	public static final short AMERITAS = 9;
	public static final short MUTUAL = 10;
	public static final short EYEMED = 11;
	public static final short CIGNA = 12;
	public static final short CAREMARK = 13;
	public static final short CBG = 14;
	public static final short AETNA = 15;
	public static final short MADISON_DENTAL = 16;
	public static final short PRISM_EXPORT = 17;  //  Graded Benefit Whole Life
	public static final short NORTH_AMERICA_ADMINISTRATORS = 18;

	@OneToMany(mappedBy = HrBenefit.BENEFIT_PROVIDER, fetch = FetchType.LAZY)
	@org.hibernate.annotations.Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
	public Set<HrBenefit> getBenefitsProvided() {
		return benefitsProvided;
	}

	public void setBenefitsProvided(Set<HrBenefit> benefitsProvided) {
		this.benefitsProvided = benefitsProvided;
	}

	// Constructors
	/**
	 * default constructor
	 */
	public VendorCompany() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dflt_ap_acct")
	public GlAccount getGlAccountByDfltApAcct() {
		return this.glAccountByDfltApAcct;
	}

	public void setGlAccountByDfltApAcct(final GlAccount glAccountByDfltApAcct) {
		this.glAccountByDfltApAcct = glAccountByDfltApAcct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dflt_expense_acct")
	public GlAccount getGlAccountByDfltExpenseAcct() {
		return this.glAccountByDfltExpenseAcct;
	}

	public void setGlAccountByDfltExpenseAcct(
			final GlAccount glAccountByDfltExpenseAcct) {
		this.glAccountByDfltExpenseAcct = glAccountByDfltExpenseAcct;
	}

	@Column(name = "account_number")
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(final String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public CompanyDetail getAssociatedCompany() {
		return associatedCompany;
	}

	public void setAssociatedCompany(CompanyDetail associatedCompany) {
		this.associatedCompany = associatedCompany;
	}

	@Column(name = "interface_id")
	public short getInterfaceId() {
		return interfaceId;
	}

	public void setInterfaceId(short interfaceId) {
		this.interfaceId = interfaceId;
	}

	@Override
	public boolean equals(Object o) {
		if (getOrgGroupId() == null && o == null)
			return true;
		if (getOrgGroupId() != null && o instanceof VendorCompany)
			return getOrgGroupId().equals(((VendorCompany) o).getOrgGroupId());

		return false;
	}

	@Override
	public int hashCode() {
		if (getOrgGroupId() == null)
			return 0;
		return getOrgGroupId().hashCode();
	}

	@Override
	public String notifyId() {
		return getOrgGroupId();
	}

	@Override
	public String notifyClassName() {
		return "VendorCompany";
	}
}
