#!/usr/bin/bash

# This one runs a groovy program while including the Stack360 class files
# It is run from the development environment


if [ $# -ne 1 ]; then
    echo usage: $0 [groovy file name without .groovy]
    exit 1
fi
 
libs=`echo ../../lib/{Kiss,json,postgresql-42.5.4,bcpg-jdk15-145,bcprov-jdk15-145,log4j-1.2-api-2.17.2,log4j-api-2.17.2,log4j-core-2.17.2,commons-compress-1.20}.jar`
dd=${libs// /:}
groovy -cp $dd:../../build/web/WEB-INF/classes $1

